//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAdvance
    {
        public int EmployeeAdvanceID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string AdvanceDate { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<int> IsPaid { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
