//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesType
    {
        public int ExpensesTypeID { get; set; }
        public string ExpensesTypeName { get; set; }
        public string IsDeleted { get; set; }
    }
}
