//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int ProductCategoryID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
