//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public int ProdcutCategoryID { get; set; }
        public string ProductName { get; set; }
        public string BrandNameID { get; set; }
        public string ModelID { get; set; }
        public string GenerationID { get; set; }
        public string RamID { get; set; }
        public string HardDiskID { get; set; }
        public string ProcessorID { get; set; }
        public string ProductImage { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string BarCode { get; set; }
    }
}
