//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfitAndLoss
    {
        public int ProfitAndLossID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> PurchaseDetailID { get; set; }
        public Nullable<int> SalesID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
