//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int SalaryID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public string SalaryMonth { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
