//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string FullName { get; set; }
        public string DOB { get; set; }
        public string DOJ { get; set; }
        public string CNIC { get; set; }
        public string UserImage { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
